import { v4 as uuidv4 } from 'https://jspm.dev/uuid';

export const boopData = [
	{
		handle: "@yoshi-saurus 🍎🦖",
		profilePic: "img/yoshi_avatar.png",
		likes: 91,
		reBoop: 4,
		boopText: "Give me 🍎 and no one gets hurt. Rawr!",
		replies: [
			{
				handle: "@denim-denim-denim 👖✅",
				profilePic: "img/mario_avatar.png",
				boopText: "Yoshi, buddy we've talked about this. You can't keep demanding more fruit!",
			},
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
	{
		handle: "@Mushroom-Peach 🍄👑",
		profilePic: "img/princessPeach_avatar.png",
		likes: 985,
		reBoop: 462,
		boopText: "I am in need of a couple brave heroes to help with a Koopa problem in the Mushroom Kingdom. DM me for details!",
		replies: [
			{
				handle: "@dragonBorn ✅",
				profilePic: "img/skyrimGuy_avatar.png",
				boopText: "At your service! My cousins are out fighting dragons and I'm on guard duty but I can spare some time. Sign me up!",
			},
			{
				handle: "@silentButDeadly ✅",
				profilePic: "img/ezio_avatar.png",
				boopText: "Show me to your highest tower and I can survey the land for these Koopas. Sending you a DM now 📩",
			},
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
	{
		handle: "@FalconPunch 🪖",
		profilePic: "img/captainFalcon_avatar.png",
		likes: 80,
		reBoop: 6,
		boopText: "Looking for some help on how to do a barrel roll. Any insight would be welcome.",
		replies: [
			{
				handle: "@theRealDragonBorn 🔥",
				profilePic: "img/spyro_avatar.png",
				boopText: "Have you tried tucking your wings in and rolling?",
			},
			{
				handle: "@DK_RapGod 🎙🍌",
				profilePic: "img/dk_avatar.png",
				boopText: "I can show you how to roll a barrel 🤷‍♂️",
			},
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
	{
		handle: "@iBandiCan ✅",
		profilePic: "img/crash_avatar.png",
		likes: 4,
		reBoop: 13,
		boopText: "Whether it's chasing down wumpa fruit or speeding on carts, the answer is yes. Remember that.",
		replies: [
			{
				handle: "@yoshi-saurus 🍎🦖",
				profilePic: "img/yoshi_avatar.png",
				boopText: "I couldn't agree more!",
			},
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
	{
		handle: "@BlockBruiser",
		profilePic: "img/steve_avatar.png",
		likes: 239,
		reBoop: 142,
		boopText: "Looking for easy ways to tone up for the summer? DM me for a special limited time offer on how to harness the power of blocks.",
		replies: [
			{
				handle: "@ProudPapa ✅",
				profilePic: "img/kratos_avatar.png",
				boopText: "Would this work for full-time Dad's too? Looking for ways to get back into shape!",
			},
			{
				handle: "@DK_RapGod 🎙🍌",
				profilePic: "img/dk_avatar.png",
				boopText: "As long as it doesn't restrict my bananna consumption, I'm open.",
			},
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
	{
		handle: "@IamSpeed ✅",
		profilePic: "img/sonic_avatar.png",
		likes: 619,
		reBoop: 395,
		boopText: "Proud to say I've once again beaten @denim-denim-denim 👖✅ at the Olympics. Now to celebrate with some delicious chili cheese dogs!",
		replies: [
			{
				handle: "@theRealDragonBorn 🔥",
				profilePic: "img/spyro_avatar.png",
				boopText: "Congratulations but just remember I wasn't there...until then, we'll never know who's the absolute best!",
			},
			{
				handle: "@denim-denim-denim 👖✅",
				profilePic: "img/mario_avatar.png",
				boopText: "You might have won this year but wait until Swole Summer! I'm going to pack on some muscle and we'll see who's laughing then!",
			},
			{
				handle: "@hyrule-hero",
				profilePic: "img/link_avatar.png",
				boopText: "Always a fun competition! I guess my invitation just got lost on the way...",
			},
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
	{
		handle: "@SpaceFox",
		profilePic: "img/fox_avatar.png",
		likes: 4,
		reBoop: 1,
		boopText: "I'm only here so I don't get fined.",
		replies: [
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
	{
		handle: "@ProudPapa ✅",
		profilePic: "img/kratos_avatar.png",
		likes: 873,
		reBoop: 486,
		boopText: "Don't be sorry, be better. That is all.",
		replies: [
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
	{
		handle: "@hyrule-hero",
		profilePic: "img/link_avatar.png",
		likes: 502,
		reBoop: 85,
		boopText: "You know you're an adult when you suddenly start taking Bert's side over Ernie's.",
		replies: [
			{
				handle: "@theRealDragonBorn 🔥",
				profilePic: "img/spyro_avatar.png",
				boopText: "😂😂😂",
			},
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
	{
		handle: "@RoboCrusher",
		profilePic: "img/megaman_avatar.png",
		likes: 36,
		reBoop: 5,
		boopText: "I don't want to die doing something I love. I want to die doing something I hate. That way I don't have to finish it.",
		replies: [
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
	{
		handle: "@NomNomNom",
		profilePic: "img/pacman_avatar.png",
		likes: 914,
		reBoop: 475,
		boopText: "Shower thought: Who called it your foot falling asleep and not coma toes?",
		replies: [
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
	{
		handle: "@ShockToMeetYa",
		profilePic: "img/pikachu_avatar.png",
		likes: 490,
		reBoop: 164,
		boopText: "Just heard a guy at the dog park near Pallet Town tell his dog “NO!” and then more quietly, “We talked about this!”",
		replies: [
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
	{
		handle: "@BountyHunterBoss",
		profilePic: "img/samus_avatar.png",
		likes: 432,
		reBoop: 153,
		boopText: "How does the little mermaid decide which creatures are her friends and which ones are her bra?",
		replies: [
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
	{
		handle: "@dragonBorn ✅",
		profilePic: "img/skyrimGuy_avatar.png",
		likes: 849,
		reBoop: 340,
		boopText: "Commercial comes on the TV. Me, as a kid: Hey, I have that toy! Me, as an adult: Hey, I’m on that medication.",
		replies: [
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
	{
		handle: "@Aspiring-UPSWorker 📦",
		profilePic: "img/solidSnake_avatar.png",
		likes: 740,
		reBoop: 357,
		boopText: "Every time I almost think humanity will be okay, I see someone struggle with the self-checkout for 20 minutes.",
		replies: [
		],
		isLiked: false,
		isBooped: false,
		uuid: uuidv4(),
	},
];
